Repository blyndusk/flamingops, pull requests merged in 2022-03, with the labels that each got.

#29 ops: docker + CI/CD
  .github/workflows/cd.go.yml
  .github/workflows/cd.web.yml
  .github/workflows/ci.go.yml
  .github/workflows/ci.web.yml
  README.md
  build/package/sample-api/.air.conf
  build/package/web/Dockerfile.loc
  build/package/web/Dockerfile.prod
  build/package/web/default.conf
  deploy/docker-compose.yml
  scripts/start.sh
  web/_docs/.gitkeep.md
  web/package-lock.json
  web/package.json
Labels: react, docker, feat, cicd, doc

#31 feat(web): #17 - add a bit of a clean template
  web/src/components/dashboard/dashboard-navbar.tsx
  web/src/pages/dashboard/index.tsx
Labels: feat

#19 add(db): #12 - Create models
  internal/controllers/fixtures.go
  internal/database/migration.go
  internal/middlewares/users.go
  pkg/models/awsCredentials.go
  pkg/models/awsServicesDatas.go
  pkg/models/displayPreferences.go
  pkg/models/swCredentials.go
  pkg/models/swServicesDatas.go
  pkg/models/users.go
Labels: go, DONT MERGE !!

#23 ops - k8s / helm / terraform / docker implementation
  .github/workflows/cd.go.yml
  .github/workflows/cd.web.yml
  .github/workflows/md.release.yml
  .gitignore
  build/package/sample-api/Dockerfile
  build/package/web/Dockerfile.prod
  deploy/docker-compose.yml
  deploy/kubernetes/.gitignore
  deploy/kubernetes/charts/flamingops-api/Chart.yaml
  deploy/kubernetes/charts/flamingops-api/README.md
  deploy/kubernetes/charts/flamingops-api/templates/_helpers.tpl
  deploy/kubernetes/charts/flamingops-api/templates/configmap.yaml
  deploy/kubernetes/charts/flamingops-api/templates/deploy.yaml
  deploy/kubernetes/charts/flamingops-api/templates/ingress.yaml
  deploy/kubernetes/charts/flamingops-api/templates/sealed-secret-certs.yaml
  deploy/kubernetes/charts/flamingops-api/templates/sealed-secret.yaml
  deploy/kubernetes/charts/flamingops-api/templates/service.yaml
  deploy/kubernetes/charts/flamingops-api/templates/serviceaccount.yaml
  deploy/kubernetes/charts/flamingops-api/values-prod.yaml
  deploy/kubernetes/charts/flamingops-api/values.yaml
  deploy/kubernetes/charts/flamingops-ui/Chart.yaml
  deploy/kubernetes/charts/flamingops-ui/README.md
  deploy/kubernetes/charts/flamingops-ui/templates/_helpers.tpl
  deploy/kubernetes/charts/flamingops-ui/templates/configmap.yaml
  deploy/kubernetes/charts/flamingops-ui/templates/deploy.yaml
  deploy/kubernetes/charts/flamingops-ui/templates/entrypoint-configmap.yaml
  deploy/kubernetes/charts/flamingops-ui/templates/ingress.yaml
  deploy/kubernetes/charts/flamingops-ui/templates/service.yaml
  deploy/kubernetes/charts/flamingops-ui/templates/serviceaccount.yaml
  deploy/kubernetes/charts/flamingops-ui/values-prod.yaml
  deploy/kubernetes/charts/flamingops-ui/values.yaml
  deploy/kubernetes/infra/cluster/cert-manager/cluster-issuer.yaml
  deploy/kubernetes/infra/cluster/cluster-cert.pem
  deploy/kubernetes/infra/cluster/registry-sealed-secret.yaml
  deploy/terraform/.env.sample
  deploy/terraform/.gitignore
  deploy/terraform/eks-cluster.tf
  deploy/terraform/kubernetes-dashboard-admin.rbac.yaml
  deploy/terraform/kubernetes.tf
  deploy/terraform/outputs.tf
  deploy/terraform/provider.tf
  deploy/terraform/security-groups.tf
  deploy/terraform/variables.tf
  deploy/terraform/versions.tf
  deploy/terraform/vpc.tf
  scripts/start.sh
Labels: docker, feat, cicd, doc

#35 Feat ops
  .github/CODEOWNERS
  .github/workflows/cd.api.yml
  .github/workflows/cd.ui.yml
  .github/workflows/ci.api.yml
  .github/workflows/ci.ui.yml
  cmd/sample-api/main.go
Labels: go, cicd

#33 go - implement various controllers
  cmd/sample-api/main.go
  internal/controllers/activeServices.go
  internal/controllers/awsServicesData.go
  internal/controllers/displayPreferences.go
  internal/controllers/swServicesData.go
  internal/database/migration.go
  internal/middlewares/activeServices.go
  internal/middlewares/awsServicesData.go
  internal/middlewares/displayPreferences.go
  internal/middlewares/swServicesData.go
  internal/middlewares/users.go
  internal/router/router.go
  pkg/models/activeServices.go
  pkg/models/awsCredentials.go
  pkg/models/awsServicesDatas.go
  pkg/models/displayPreferences.go
  pkg/models/swCredentials.go
  pkg/models/swServicesDatas.go
Labels: go, feat, [US] developer

#32 web - api call + jwt
  README.md
  go.mod
  go.sum
  internal/controllers/users.go
  internal/middlewares/jwt.go
  internal/middlewares/secretsManager.go
  internal/middlewares/users.go
  internal/router/router.go
  internal/utils/jwt_utils.go
  pkg/forms/user.go
  pkg/models/login.go
  pkg/models/users.go
  web/src/__fake-api__/auth-api.ts
  web/src/contexts/amplify-context.tsx
  web/src/contexts/auth0-context.tsx
  web/src/contexts/firebase-auth-context.tsx
  web/src/contexts/jwt-context.tsx
  web/src/types/user.ts
  web/yarn.lock
Labels: react, go, doc

#40 fix(middleware): #15 - fix
  cmd/sample-api/main.go
  internal/middlewares/activeServices.go
  internal/middlewares/awsServicesData.go
  internal/middlewares/requestedRegions.go
  internal/middlewares/swServicesData.go
Labels: go

#43 fix(jwt): #42 - remove json from middlewares
  internal/controllers/secretsManager.go
  internal/controllers/users.go
  internal/middlewares/secretsManager.go
  internal/middlewares/users.go
  internal/router/router.go
  pkg/forms/user.go
Labels: go

#38 wiki - implementation
  LICENSE
  Makefile
  README.md
  docs/wiki/CI_CD.md
  docs/wiki/Home.md
  docs/wiki/_Sidebar.md
  docs/wiki/contributing.md
  docs/wiki/conventions.md
  docs/wiki/folder_structure.md
  docs/wiki/project_setup.md
Labels: feat, doc

#45 Feat(worker): #16 - implements scheduler and rate limiting
  cmd/sample-api/main.go
  internal/queue/scheduler.go
  internal/queue/sendMessage.go
Labels: go

#49 Fix user routes and clean middlewares
  internal/controllers/activeServices.go
  internal/controllers/awsServicesData.go
  internal/controllers/requestedRegions.go
  internal/controllers/swServicesData.go
  internal/controllers/users.go
  internal/middlewares/activeServices.go
  internal/middlewares/awsServicesData.go
  internal/middlewares/requestedRegions.go
  internal/middlewares/swServicesData.go
  internal/middlewares/users.go
  internal/router/router.go
Labels: bug, go, [US] developer

#51 ops - fixes
  .DS_Store
  Makefile
  README.md
  deploy/kubernetes/.gitignore
  deploy/kubernetes/charts/flamingops-api/templates/deploy.yaml
  deploy/kubernetes/charts/flamingops-api/templates/sealed-secret-certs.yaml
  deploy/kubernetes/charts/flamingops-api/templates/secret.yaml
  deploy/kubernetes/charts/flamingops-api/templates/serviceaccount.yaml
  deploy/kubernetes/charts/flamingops-api/values.yaml
  deploy/kubernetes/charts/flamingops-ui/templates/serviceaccount.yaml
  deploy/kubernetes/infra/cluster/cluster-cert.pem
  deploy/kubernetes/infra/cluster/mycert.pem
  deploy/terraform/.terraform.lock.hcl
  deploy/terraform/lambda.tf
  deploy/terraform/outputs.tf
  deploy/terraform/provider.tf
  deploy/terraform/rds.tf
  deploy/terraform/sqs.tf
  deploy/terraform/variables.tf
  deploy/terraform/vpc.tf
Labels: feat, doc

#54 Fix jwt verification
  internal/controllers/sqsHandler.go
  internal/middlewares/activeServices.go
  internal/middlewares/awsServicesData.go
  internal/middlewares/jwt.go
  internal/middlewares/requestedRegions.go
  internal/middlewares/swServicesData.go
  internal/middlewares/users.go
  internal/router/router.go
  internal/utils/jwt_utils.go
Labels: bug, go, [US] developer

#55 feat(user): #53 - hash passwords
  internal/middlewares/users.go
Labels: go, [US] developer
